name: abdulsmith
favicon: null
layout_spectrum: 0.08305
typography_spectrum: 0.39999
title: Abdul Smith Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343434'
    - '#b3b3b3'
    - '#858585'
    - '#656565'
    - '#4f4f4f'
  brandStrength: 0
  lightness: 0
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
