name: abdulsmith
favicon: null
layout_spectrum: 0.30049
typography_spectrum: 0.39999
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7822223275434226
  lightness: 0.5011385348625481
  saturation: 0.5737779191695154
  rhythmicContrast: 0.3235663080122322
purpose: []
