name: abdulsmith
favicon: null
layout_spectrum: 0.64657
typography_spectrum: 0.44831
title: Abdul Smith Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343434'
    - '#b3b3b3'
    - '#858585'
    - '#656565'
    - '#4f4f4f'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
