name: abdulsmith
favicon: null
layout_spectrum: 0.30049
typography_spectrum: 0.39999
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343434'
    - '#b3b3b3'
    - '#858585'
    - '#656565'
    - '#4f4f4f'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
